=== Trust1Team/t1c-lib-java/src/main/resources/schemas/DsInfoResponse.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "id": "DsInfoResponse",
  "properties": {
    "configFile": {
      "type": "string"
    },
    "build": {
      "type": "string"
    },
    "version": {
      "type": "string"
    },
    "environemnt": {
      "type": "string"
    },
    "storageAppName": {
      "type": "string"
    },
    "storageServiceAccount": {
      "type": "string"
    },
    "storageCertPath": {
      "type": "string"
    },
    "storageBucket": {
      "type": "string"
    },
    "storageDownloadPrefix": {
      "type": "string"
    },
    "fileOsx": {
      "type": "string"
    },
    "fileWin32": {
      "type": "string"
    },
    "fileWin64": {
      "type": "string"
    },
    "fileDefaultVersion": {
      "type": "string"
    },
    "securityEnabled": {
      "type": "string"
    },
    "securityPrivateKeyAvailable": {
      "type": "boolean"
    }
  }
}

=== Trust1Team/t1c-lib-java/src/test/resources/responses/DsSystemStatus.json
{
  "configFile": "application_acc",
  "build": "2017-11-27 20:16:50",
  "version": "0.5.6",
  "environemnt": "ACC",
  "storageAppName": "[[Trust1Team-GCL-Distribution/1.0]]",
  "storageServiceAccount": "t1c-ds-acc@t1t-saas-signbox.iam.gserviceaccount.com",
  "storageCertPath": "/usr/local/t1c-ds/t1t-saas-signbox-baf665c1dc48.p12",
  "storageBucket": "gcl-distro",
  "storageDownloadPrefix": "https://storage.googleapis.com/gcl-distro/",
  "fileOsx": "Trust1Connector.dmg",
  "fileWin32": "Trust1Connector_x86.msi",
  "fileWin64": "Trust1Connector_x64.msi",
  "fileDefaultVersion": "v1.2.5",
  "securityEnabled": "false",
  "securityPrivateKeyAvailable": true
}
